###

GET http://localhost:3006/notes

###
POST  http://localhost:3006/notes
Content-Type: application/json

{
    "title" : "Tugas Backend CRUD",
    "note" : "Biasakan untuk selalu berterima kasih kepada siapapun"
}

###
PUT http://localhost:3006/notes/title/2
Content-Type: application/json

{
    "title" : "Project Swarakama",
}